# Generated by Django 4.0.5 on 2022-09-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_publicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='publicity',
        ),
    ]
