# Generated by Django 4.0.5 on 2022-10-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
